# Generated by Django 4.2.20 on 2025-04-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0003_membership"),
    ]

    operations = [
        migrations.RemoveField(model_name="candidate", name="election",),
        migrations.AddField(
            model_name="candidate",
            name="club",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="voting.club",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="election",
            name="candidates",
            field=models.ManyToManyField(
                blank=True, related_name="elections", to="voting.candidate"
            ),
        ),
    ]
