# Generated by Django 4.2.20 on 2025-04-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0004_remove_candidate_election_candidate_club_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election", name="end_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="election", name="start_date", field=models.DateField(),
        ),
    ]
