# Generated by Django 4.2.20 on 2025-04-02 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voting", "0005_alter_election_end_date_alter_election_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "faculty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADA", "Art, Design and Architecture"),
                            ("ART", "Arts"),
                            ("BUS", "Business and Economics"),
                            ("EDU", "Education"),
                            ("ENG", "Engineering"),
                            ("IT", "Information Technology"),
                            ("LAW", "Law"),
                            ("MED", "Medicine, Nursing and Health Sciences"),
                            ("PHAR", "Pharmacy and Pharmaceutical Sciences"),
                            ("SCI", "Science"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "level_of_education",
                    models.CharField(
                        blank=True,
                        choices=[("UG", "Undergraduate"), ("PG", "Postgraduate")],
                        max_length=2,
                    ),
                ),
                (
                    "campus_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLAYTON", "Clayton"),
                            ("CAULFIELD", "Caulfield"),
                            ("PENINSULA", "Peninsula"),
                            ("PARKVILLE", "Parkville"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("STUDENT", "Student"), ("STAFF", "Staff")],
                        default="STUDENT",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
