# Generated by Django 4.2.20 on 2025-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0007_remove_election_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Ongoing", "Ongoing"),
                    ("Ended", "Ended"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
