# Generated by Django 4.2.20 on 2025-05-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0008_election_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="election", name="status",),
        migrations.AddField(
            model_name="election",
            name="approval_status",
            field=models.CharField(
                choices=[("Pending", "Pending Approval"), ("Approved", "Approved")],
                default="Pending",
                help_text="Has an admin approved this election?",
                max_length=20,
            ),
        ),
    ]
