"""
Django settings for monash_voting project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2trzc=_&2egqk0r59$)8=6k0=1rhcll*tju61ph+t_%5tnr5wa"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#Remove before deployment 
ALLOWED_HOSTS = ["*"]

#For depolyment
#ALLOWED_HOSTS = ["mvs-a8ezevgga2are8g2.australiasoutheast-01.azurewebsites.net"]

#CSRF_TRUSTED_ORIGINS = [
#    "https://mvs-a8ezevgga2are8g2.australiasoutheast-01.azurewebsites.net",
#]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "voting",  
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "monash_voting.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "monash_voting.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Remove to use simple password for demo
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

#AUTH_PASSWORD_VALIDATORS = [
#    {
#        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#    },
#    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
#    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
#    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
#]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Australia/Melbourne"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Who gets the mail_admins() notifications
ADMINS = [
    ("Admin", "admin@staff.monash.edu"),
]

# What “From:” address to use for those emails
SERVER_EMAIL = "no-reply@mvs.monash.edu"


# Send all emails to the console for development/demo
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'